fix: Ensure linting always applied.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,7 +25,16 @@ jobs:
 
       - name: Run lint
         run: |
-          make lint
+          # Ensure linting fails the build if issues are found
+          make lint || exit 1  
+
+      - name: Auto-format code
+        run: |
+          make format
+      - uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: "Automatically formatted code"
+          branch: ${{ github.head_ref }}
 
   bats:
     runs-on: ubuntu-24.04
@@ -149,8 +158,3 @@ jobs:
            make validate
            pipx install .
            make bats-nocontainer
-
-# FIXME: ci script should be able to run on MAC.
-#      - name: Run ci
-#        shell: bash
-#        run: make ci
